export const HEADERS_ACCEPTS = {
  applicationAtomXml: 'application/atom+xml',
  applicationEcmascript: 'application/ecmascript',
  applicationJavascript: 'application/javascript',
  applicationJson: 'application/json',
  applicationOctetStream: 'application/octet-stream',
  applicationXml: 'application/xml',
  applicationOgg: 'application/ogg',
  applicationPdf: 'application/pdf',
  applicationExcel: 'application/excel',
  applicationPostScript: 'application/postscript',
  applicationRdfXml: 'application/rdf+xml',
  applicationRssXml: 'application/rss+xml',
  applicationSoapXml: 'application/soap+xml',
  applicationFontWoff: 'application/font-woff',
  applicationXYaml: 'application/x-yaml',
  applicationZip: 'application/zip',
  applicationGzip: 'application/gzip',
  imageGif: 'image/gif',
  imageJpeg: 'image/jpeg',
  imagePng: 'image/png',
  textCsv: 'text/csv',
  textHtml: 'text/html',
  textPlain: 'text/plain',
  textXml: 'text/xml',
}
